### ISSUE TITLE
Metaworld experiments do not run due to BilevelEpsilonGreedy

### ISSUE THREAD

**Issue by Lan131** [UT-Austin-RPL/amago#62]
Hello, we are looking to cite your paper and replicate the ML45 results but they don't seem to work. We have followed the installation instructions and are running this command:

python ./examples/05_kshot_metaworld.py --run_name "first" --benchmark ml45 --buffer_dir ./buffer --parallel_actors 30 --memory_size 320 --timesteps_per_epoch 1501 --agent_type multitask

From the amago-main directory

when we do that we get this error:
Traceback (most recent call last):
  File "/home/research/lanier.m/Desktop/amago-main/./examples/05_kshot_metaworld.py", line 76, in <module>
    experiment.start()
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 109, in start
    self.init_envs()
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 214, in init_envs
    self.train_envs = Par(make_train)
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 144, in __init__
    dummy_env = env_fns[0]()
  File "/home/research/lanier.m/Desktop/amago-main/amago/envs/env_utils.py", line 530, in __call__
    env = SequenceWrapper(
  File "/home/research/lanier.m/Desktop/amago-main/amago/envs/env_utils.py", line 398, in __init__
    "goal": self.env.kgoal_space,
AttributeError: 'BilevelEpsilonGreedy' object has no attribute 'kgoal_space'

We can get past this by explicitly adding this to BilevelEpsilonGreedy:
    @property 
    def kgoal_space(self):
        return gym.spaces.Box(low=0.0, high=0.0, shape=(1, 1))
        
But get another error:

Traceback (most recent call last):
  File "/home/research/lanier.m/Desktop/amago-main/./examples/05_kshot_metaworld.py", line 76, in <module>
    experiment.start()
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 109, in start
    self.init_envs()
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 215, in init_envs
    self.train_envs.reset()
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 253, in reset
    return self.reset_wait()
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 326, in reset_wait
    self._raise_if_errors(successes)
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 676, in _raise_if_errors
    raise exctype(value)
TypeError: SequenceWrapper.reset() got an unexpected keyword argument 'options'

We can get past this error by adding an options=None argument to the SequenceWrapper class in env_utils.py, but we then get another error

Traceback (most recent call last):
  File "/home/research/lanier.m/Desktop/amago-main/./examples/05_kshot_metaworld.py", line 76, in <module>
    experiment.start()
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 109, in start
    self.init_envs()
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 215, in init_envs
    self.train_envs.reset()
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 253, in reset
    return self.reset_wait()
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 326, in reset_wait
    self._raise_if_errors(successes)
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 676, in _raise_if_errors
    raise exctype(value)
AttributeError: 'BilevelEpsilonGreedy' object has no attribute 'max_goal_seq_length'

It appears to be self.kgoal_space.shape[0]. I can add this explictly to the BilevelEpsilonGreedy class to get past that error but then get this when it starts to run:
Traceback (most recent call last):
  File "/home/research/lanier.m/Desktop/amago-main/./examples/05_kshot_metaworld.py", line 79, in <module>
    experiment.learn()
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 678, in learn
    self.evaluate_val()
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 494, in evaluate_val
    *_, returns, successes, specials = self.interact(
  File "/home/research/lanier.m/Desktop/amago-main/amago/learning.py", line 402, in interact
    utils.call_async_env(envs, "reset_stats")
  File "/home/research/lanier.m/Desktop/amago-main/amago/utils.py", line 72, in call_async_env
    return env.call_wait()
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 509, in call_wait
    self._raise_if_errors(successes)
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 676, in _raise_if_errors
    raise exctype(value)
AttributeError: 'SequenceWrapper' object has no attribute 'env_name'

Can you verify if the code is correct and up to date for the metaworld baseline?

**Comment by jakegrigsby** [comment]
Hey @Lan131, this is a gymnasium version control issue, you'll need `gymnasium <= 0.29`. 

This issue made me realize the NeurIPS camera ready must be public, but I haven't actually put the paper on arxiv yet or announced it etc. I've fixed this in an update to the codebase meant to be merged alongside the new paper announcement (`refactor-gc` branch). There are some minor changes that differ from the version used for the paper (which is not the public `main` branch), which has led to a delay as I verify that the results are unchanged. 

I've recently tested that the command 
```
--run_name metaworld_ml45 --benchmark ml45 --buffer_dir <buffer dir> --parallel_actors 40 --memory_size 320 --timesteps_per_epoch 1501 --agent_type multitask --max_seq_len 256 --memory_layers 3 --dset_max_size 25000 --epochs 5000 --val_interval 40
```

leads to this wandb output:

https://wandb.ai/jakegrigsby/amago-v3-reference/runs/gq9s8vxs?nw=nwuserjakegrigsby


<img width="538" alt="Screen Shot 2024-11-13 at 2 06 58 PM" src="https://github.com/user-attachments/assets/e5ae11cd-0f16-4733-a9a7-12456762fe31">


Where the paper result would be the purple curve:

<img width="412" alt="Screen Shot 2024-11-13 at 2 05 26 PM" src="https://github.com/user-attachments/assets/47fc17b9-ff36-4758-8b7e-cbbfc14df46b">

Please check back in a few days after I do some final cleanups. I can ping you on this issue.

**Comment by Lan131** [comment]
Please do. ML45 usually reports success rate here. Is this tracked in your code?

**Comment by jakegrigsby** [comment]
Yes, for all 3 meta-rollout trials across all 45 tasks. 

<img width="1600" alt="Screen Shot 2024-11-13 at 3 44 31 PM" src="https://github.com/user-attachments/assets/3d741e78-ab92-42b3-81d1-75f306ca7fcd">


It also records the total successes across all three trials per task, which are averaged to get this

<img width="385" alt="Screen Shot 2024-11-13 at 3 42 21 PM" src="https://github.com/user-attachments/assets/3afbb70b-d22a-43a9-b42c-359a21b7dce0">
59c773">


You can also plot any metric by the total frames in each individual task.

**Comment by Lan131** [comment]
So I pulled down the refactor branch and I am still getting this error:
Traceback (most recent call last):
  File "/home/research/lanier.m/Desktop/amago-refactor-gc/./examples/07_metaworld.py", line 82, in <module>
    experiment.start()
  File "/home/research/lanier.m/Desktop/amago-refactor-gc/amago/experiment.py", line 182, in start
    env_summary = self.init_envs()
  File "/home/research/lanier.m/Desktop/amago-refactor-gc/amago/experiment.py", line 327, in init_envs
    self.train_envs = Par(make_train)
  File "/home/research/lanier.m/miniconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 144, in __init__
    dummy_env = env_fns[0]()
  File "/home/research/lanier.m/Desktop/amago-refactor-gc/amago/envs/amago_env.py", line 369, in __call__
    env = SequenceWrapper(
  File "/home/research/lanier.m/Desktop/amago-refactor-gc/amago/envs/amago_env.py", line 222, in __init__
    self.reset_stats()
  File "/home/research/lanier.m/Desktop/amago-refactor-gc/amago/envs/amago_env.py", line 246, in reset_stats
    self.return_history = ReturnHistory(self.env_name)
  File "/home/research/lanier.m/Desktop/amago-refactor-gc/amago/envs/amago_env.py", line 346, in env_name
    return self.env.env_name
AttributeError: 'BilevelEpsilonGreedy' object has no attribute 'env_name'



I am running from the amago-refactor-gc :

python ./examples/07_metaworld.py --run_name metaworld_ml45 --benchmark ml45 --buffer_dir buffer --parallel_actors 40 --memory_size 320 --timesteps_per_epoch 1501 --agent_type multitask --max_seq_len 256 --memory_layers 3 --dset_max_size 25000 --epochs 5000 --val_interval 40

**Comment by jakegrigsby** [comment]
@Lan131, this is the error we get when we update to gymnasium 1.0. We still need gymnasium <= 0.29.

`pip install gymnasium==0.29.1`
 
Or run setup again on the new branch with `pip install -e .` , and it will set package versions to the range that we test.
